version: '3.5'
services:
  google-drive-api:
    container_name: google-drive-api
    build: .
    ports:
      - "2500:2500"
      - "2525:2525"
    volumes:
      - ./src:/google_drive_api/src
      - ./tests:/google_drive_api/tests
    environment:
      - PYTHONPATH=/google_drive_api/src/
    tty: true

  allure-report:
    image: "frankescobar/allure-docker-service"
    container_name: reporter
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: "TRUE"
    ports:
      - "4040:4040"
      - "5050:5050"
    volumes:
      - ./tests/reports/:/app/allure-results